# fly.toml app configuration file generated for aged-wood-2544 on 2023-09-11T05:59:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-wood-2544"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
